# Generated by Django 4.2 on 2023-07-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='Time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='Value',
            field=models.CharField(max_length=10),
        ),
    ]
